#!/bin/sh
# TASK-124 — mint the committed fMP4 goldens under src/goldens/ (offline;
# product tests never spawn ffmpeg). Pinned tool: ffmpeg/ffprobe 7.0.2
# static (lab/fmp4/PIN.md). Same structures as gen_fixtures.sh, shorter
# (2.5 s) so the committed set stays small. `fmp4_cenc` / `fmp4_2track`
# are cut at the first mdat boundary (the typed rejection fires before any
# later box is needed).
set -eu
cd "$(dirname "$0")"
G=../../src/goldens
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# 2.5 s speech-like synthetic stereo, 48 kHz (deterministic lavfi source).
SRC='aevalsrc=sin(2*PI*440*t)*0.3+sin(2*PI*1760*t)*0.1*(0.5+0.5*sin(2*PI*3*t)):sample_rate=48000:duration=2.5:channel_layout=stereo'
run() {
  ffmpeg -hide_banner -loglevel error -y -f lavfi -i "$SRC" "$@"
}

run -c:a aac -b:a 96k -movflags empty_moov -frag_duration 1000000 "$G/fmp4_lc.mp4"
run -c:a aac -b:a 96k -movflags empty_moov+default_base_moof -frag_duration 1000000 "$G/fmp4_lc_dbmoof.mp4"
run -c:a aac -b:a 96k -movflags empty_moov+omit_tfhd_offset -frag_duration 1000000 "$G/fmp4_lc_omit.mp4"
run -c:a aac -b:a 96k -movflags empty_moov+negative_cts_offsets -frag_duration 1000000 "$G/fmp4_lc_v1.mp4"
run -c:a aac -b:a 96k -movflags cmaf -frag_duration 1000000 "$G/fmp4_lc_cmaf.mp4"
run -c:a aac -b:a 96k -movflags empty_moov+global_sidx -frag_duration 1000000 "$G/fmp4_lc_sidx.mp4"
run -c:a aac -b:a 96k "$G/fmp4_lc_flat.m4a"

# HE v1 / HE v2: remux the committed explicit-ASC M4A goldens (container
# structure is ffmpeg-generated, payloads are the syom goldens' AUs).
ffmpeg -hide_banner -loglevel error -y -i "$G/he48em.m4a" \
    -c:a copy -movflags empty_moov -frag_duration 1000000 "$G/fmp4_he.mp4"
ffmpeg -hide_banner -loglevel error -y -i "$G/he2_48em.m4a" \
    -c:a copy -movflags empty_moov -frag_duration 1000000 "$G/fmp4_he2.mp4"

# DASH: separate init + media segments; init carries elst media_time 1024.
run -c:a aac -b:a 96k -f dash -seg_duration 1 -use_timeline 0 \
    -init_seg_name init.m4s -media_seg_name 'seg_$Number%02d$.m4s' "$TMP/lc.mpd"
cp "$TMP/init.m4s" "$G/fmp4_dash_init.m4s"
cp "$TMP/seg_01.m4s" "$G/fmp4_dash_seg1.m4s"
cp "$TMP/seg_02.m4s" "$G/fmp4_dash_seg2.m4s"

# Unsupported cells: encrypted (CENC) and two AAC tracks. Cut at the first
# mdat boundary; the rejection must fire on what remains.
run -c:a aac -b:a 96k -movflags empty_moov -frag_duration 1000000 \
    -encryption_scheme cenc-aes-ctr \
    -encryption_key 00112233445566778899aabbccddeeff \
    -encryption_kid 0123456789abcdeffedcba9876543210 "$TMP/cenc.mp4"
run -map 0:a -map 0:a -c:a aac -b:a 96k \
    -movflags empty_moov -frag_duration 1000000 "$TMP/2track.mp4"
python3 - "$TMP/cenc.mp4" "$G/fmp4_cenc.mp4" <<'EOF'
import struct, sys
src, dst = sys.argv[1], sys.argv[2]
d = open(src, "rb").read()
pos, cut = 0, 0
mdats = 0
while pos + 8 <= len(d):
    size, typ = struct.unpack(">I4s", d[pos:pos + 8])
    if size == 1:
        size = struct.unpack(">Q", d[pos + 8:pos + 16])[0]
    if size == 0:
        size = len(d) - pos
    pos += size
    if typ == b"mdat":
        mdats += 1
        if mdats == 1:
            cut = pos
            break
assert cut, "no mdat"
open(dst, "wb").write(d[:cut])
EOF
python3 - "$TMP/2track.mp4" "$G/fmp4_2track.mp4" <<'EOF'
import struct, sys
src, dst = sys.argv[1], sys.argv[2]
d = open(src, "rb").read()
pos, cut = 0, 0
while pos + 8 <= len(d):
    size, typ = struct.unpack(">I4s", d[pos:pos + 8])
    if size == 1:
        size = struct.unpack(">Q", d[pos + 8:pos + 16])[0]
    if size == 0:
        size = len(d) - pos
    pos += size
    if typ == b"mdat":
        cut = pos
        break
assert cut, "no mdat"
open(dst, "wb").write(d[:cut])
EOF

# TASK-126 — tfdt-less accumulation cell: box surgery on the dbmoof golden
# (drop every tfdt, shrink trun data_offset); deterministic, no ffmpeg.
python3 strip_tfdt.py "$G/fmp4_lc_dbmoof.mp4" "$G/fmp4_lc_notfdt.mp4"

# TASK-126 — third-party GPAC vector: committed copies of the PIN.md-pinned
# fetch (re-fetch per PIN.md when absent; never regenerated by ffmpeg).
if [ -f fixtures/thirdparty/bbb_init.m4a ]; then
  cp fixtures/thirdparty/bbb_init.m4a "$G/fmp4_bbb_init.m4a"
  cp fixtures/thirdparty/bbb_seg1.m4a "$G/fmp4_bbb_seg1.m4a"
fi

ls -la "$G"/fmp4_*

# TASK-126 — pin check (GOLDENS.md) and, when ffprobe is available, the
# timeline oracle: python3 gen_timeline_oracle.py
python3 verify_pins.py
