#!/usr/bin/env python3
"""Write corpus/manifest.json from in-tree goldens, synth specs, and named naturals."""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from corpus_synth import sha256_of  # noqa: E402


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def bitstream(
    cid: str,
    path: str,
    *,
    rec: str,
    cls: str,
    profile: str,
    rate: int,
    layout: str,
    samples: int,
    split: str = "dev",
    derivation: str,
    bitrate_bps: int | None = None,
) -> dict:
    p = ROOT / path
    return {
        "id": cid,
        "kind": "bitstream",
        "split": split,
        "recording_id": rec,
        "class": cls,
        "profile": profile,
        "rate": rate,
        "layout": layout,
        "bitrate_bps": bitrate_bps,
        "valid_samples": samples,
        "origin": "in-tree syom golden",
        "origin_url": path,
        "license": "MIT (syom fixture; not a licensed natural recording)",
        "redistribution": "in-tree",
        "sha256": sha256_file(p),
        "path": path,
        "derivation": derivation,
    }


def synth(
    cid: str,
    spec: dict,
    *,
    rec: str,
    cls: str,
    rate: int,
    layout: str,
    samples: int,
    split: str = "dev",
    derivation: str,
    profile: str = "pcm-source",
) -> dict:
    return {
        "id": cid,
        "kind": "generated_pcm",
        "split": split,
        "recording_id": rec,
        "class": cls,
        "profile": profile,
        "rate": rate,
        "layout": layout,
        "bitrate_bps": None,
        "valid_samples": samples,
        "origin": "deterministic generator scripts/corpus_synth.py",
        "origin_url": "scripts/corpus_synth.py",
        "license": "MIT (synthetic, no third-party recording)",
        "redistribution": "regenerate; do not store blobs",
        "sha256": sha256_of(spec),
        "generator": spec,
        "derivation": derivation,
    }


def natural(
    cid: str,
    *,
    rec: str,
    cls: str,
    origin_url: str,
    license: str,
    split: str,
    rate: int | None,
    layout: str,
    note: str,
    languages: str,
) -> dict:
    return {
        "id": cid,
        "kind": "external_natural",
        "split": split,
        "recording_id": rec,
        "class": cls,
        "profile": "pcm-source",
        "rate": rate,
        "layout": layout,
        "bitrate_bps": None,
        "valid_samples": None,
        "origin": "external catalog; not in this checkout",
        "origin_url": origin_url,
        "license": license,
        "redistribution": "do-not-vendor; obtain offline with attribution",
        "sha256": None,
        "cache_path": None,
        "languages": languages,
        "derivation": note,
        "presence": "gap-until-obtained",
    }


def cases() -> list[dict]:
    out: list[dict] = []
    # In-tree bitstreams (dev fixtures; already used by unit tests).
    out += [
        bitstream(
            "lc-sine48-adts",
            "src/goldens/sine48.adts",
            rec="syom-golden-sine48",
            cls="tonal",
            profile="lc",
            rate=48_000,
            layout="mono",
            samples=13_312,
            derivation="committed LC sine ADTS; oracle src/goldens/sine48_48k.s16",
        ),
        bitstream(
            "lc-sine441-m4a",
            "src/goldens/sine441.m4a",
            rec="syom-golden-sine441",
            cls="tonal",
            profile="lc",
            rate=44_100,
            layout="mono",
            samples=11_264,
            derivation="committed LC 44.1 kHz M4A with elst skip; oracle sine441_44k.s16",
        ),
        bitstream(
            "lc-tns48-adts",
            "src/goldens/tns48.adts",
            rec="syom-golden-tns48",
            cls="tonal",
            profile="lc",
            rate=48_000,
            layout="mono",
            samples=1_024,
            derivation="TNS tool golden; oracle tns48_48k.s16",
        ),
        bitstream(
            "lc-pns48-adts",
            "src/goldens/pns48.adts",
            rec="syom-golden-pns48",
            cls="noise-like",
            profile="lc",
            rate=48_000,
            layout="mono",
            samples=13_312,
            derivation="PNS tool golden; oracle pns48.s16",
        ),
        bitstream(
            "he-he48-adts",
            "src/goldens/he48.adts",
            rec="syom-golden-he48",
            cls="tonal",
            profile="he-v1",
            rate=48_000,
            layout="stereo",
            samples=18_432,
            derivation="HE ADTS; SBR (+ implicit PS under unbounded split)",
        ),
        bitstream(
            "he-he48-m4a",
            "src/goldens/he48.m4a",
            rec="syom-golden-he48",
            cls="tonal",
            profile="he-v1",
            rate=48_000,
            layout="stereo",
            samples=16_320,
            derivation="HE M4A of the same recording_id as he48.adts",
        ),
        bitstream(
            "he-he48-latm",
            "src/goldens/he48.latm",
            rec="syom-golden-he48",
            cls="tonal",
            profile="he-v1",
            rate=48_000,
            layout="stereo",
            samples=18_432,
            derivation="HE LATM of the same recording_id as he48.adts",
        ),
        bitstream(
            "he-ps48-adts",
            "src/goldens/ps48.adts",
            rec="syom-golden-ps48",
            cls="tonal",
            profile="he-v2",
            rate=48_000,
            layout="stereo",
            samples=53_248,
            derivation="HE v2 PS ADTS; oracle ps48.s16",
        ),
        bitstream(
            "he-ps48-m4a",
            "src/goldens/ps48.m4a",
            rec="syom-golden-ps48",
            cls="tonal",
            profile="he-v2",
            rate=48_000,
            layout="stereo",
            samples=51_136,
            derivation="HE v2 PS M4A of the same recording_id as ps48.adts",
        ),
        bitstream(
            "lc-latm48",
            "src/goldens/latm48.latm",
            rec="syom-golden-latm48",
            cls="tonal",
            profile="lc",
            rate=48_000,
            layout="mono",
            samples=13_312,
            derivation="LC LATM; oracle latm48.s16",
        ),
        bitstream(
            "lc-lecture-m4a",
            "src/goldens/lecture.m4a",
            rec="syom-golden-lecture",
            cls="speech",
            profile="lc",
            rate=48_000,
            layout="stereo",
            samples=12 * 1024,
            derivation="in-tree lecture speech M4A (short fixture, not a licensed corpus excerpt)",
        ),
        bitstream(
            "lc-mc30-adts",
            "src/goldens/mc30.adts",
            rec="syom-golden-mc30",
            cls="multichannel-impulse",
            profile="lc",
            rate=48_000,
            layout="3.0",
            samples=20_480,
            derivation="LC 3.0; oracle mc30.s16",
        ),
        bitstream(
            "lc-mc40-adts",
            "src/goldens/mc40.adts",
            rec="syom-golden-mc40",
            cls="multichannel-impulse",
            profile="lc",
            rate=48_000,
            layout="4.0",
            samples=20_480,
            derivation="LC 4.0; oracle mc40.s16",
        ),
        bitstream(
            "lc-mc50-adts",
            "src/goldens/mc50.adts",
            rec="syom-golden-mc50",
            cls="multichannel-impulse",
            profile="lc",
            rate=48_000,
            layout="5.0",
            samples=20_480,
            derivation="LC 5.0; oracle mc50.s16",
        ),
        bitstream(
            "lc-mc51-adts",
            "src/goldens/mc51.adts",
            rec="syom-golden-mc51",
            cls="multichannel-impulse",
            profile="lc",
            rate=48_000,
            layout="5.1",
            samples=20_480,
            derivation="LC 5.1 ADTS; oracle mc51.s16",
        ),
        bitstream(
            "lc-mc51-m4a",
            "src/goldens/mc51.m4a",
            rec="syom-golden-mc51",
            cls="multichannel-impulse",
            profile="lc",
            rate=48_000,
            layout="5.1",
            samples=19_456,
            derivation="LC 5.1 M4A of the same recording_id as mc51.adts",
        ),
        bitstream(
            "enc-enc48-adts",
            "src/goldens/enc48.adts",
            rec="syom-enc48-source",
            cls="tonal+tremolo",
            profile="lc",
            rate=48_000,
            layout="stereo",
            samples=29_696,
            bitrate_bps=128_000,
            derivation="encoder golden ADTS; lavc pcm enc48.lavc.s16",
        ),
        bitstream(
            "enc-enc48m-m4a",
            "src/goldens/enc48m.m4a",
            rec="syom-enc48-source",
            cls="tonal+tremolo",
            profile="lc",
            rate=48_000,
            layout="stereo",
            samples=28_672,
            bitrate_bps=128_000,
            derivation="encoder M4A of the same source as enc48.adts",
        ),
        bitstream(
            "enc-enc48t-adts",
            "src/goldens/enc48t.adts",
            rec="syom-enc48t-source",
            cls="transient",
            profile="lc",
            rate=48_000,
            layout="stereo",
            samples=29_696,
            bitrate_bps=128_000,
            derivation="transient encoder golden",
        ),
        bitstream(
            "enc-enc48l-adts",
            "src/goldens/enc48l.adts",
            rec="syom-enc48t-source",
            cls="transient",
            profile="lc",
            rate=48_000,
            layout="stereo",
            samples=29_696,
            bitrate_bps=128_000,
            derivation="lookahead encoder golden of the same source as enc48t",
        ),
        bitstream(
            "lc-engine-sine-adts",
            "src/engine/goldens/sine.adts",
            rec="syom-engine-sine",
            cls="tonal",
            profile="lc",
            rate=48_000,
            layout="mono",
            samples=1_024,
            derivation="engine-level sine ADTS; oracle sine.s16",
        ),
        bitstream(
            "lc-engine-noise-adts",
            "src/engine/goldens/noise.adts",
            rec="syom-engine-noise",
            cls="noise-like",
            profile="lc",
            rate=48_000,
            layout="mono",
            samples=1_024,
            derivation="engine-level noise ADTS; oracle noise.s16",
        ),
    ]

    # Generated boundary PCM (named cases from DOC-3).
    out += [
        synth(
            "synth-silence-1024",
            {"fn": "silence", "n": 1024, "ch": 1, "rate": 48000},
            rec="synth-silence",
            cls="silence",
            rate=48_000,
            layout="mono",
            samples=1024,
            derivation="1024 zeros",
        ),
        synth(
            "synth-near-silence",
            {"fn": "tiny", "n": 2048, "ch": 1, "rate": 48000},
            rec="synth-tiny",
            cls="near-silence",
            rate=48_000,
            layout="mono",
            samples=2048,
            derivation="1e-20 finite amplitude",
        ),
        synth(
            "synth-impulse-first",
            {"fn": "impulse", "n": 2048, "at": 0, "ch": 1, "rate": 48000},
            rec="synth-impulse",
            cls="window-boundary-impulse",
            rate=48_000,
            layout="mono",
            samples=2048,
            derivation="impulse at sample 0",
        ),
        synth(
            "synth-impulse-1023",
            {"fn": "impulse", "n": 2048, "at": 1023, "ch": 1, "rate": 48000},
            rec="synth-impulse",
            cls="window-boundary-impulse",
            rate=48_000,
            layout="mono",
            samples=2048,
            derivation="impulse at sample 1023 (long-window tail)",
        ),
        synth(
            "synth-impulse-1024",
            {"fn": "impulse", "n": 2048, "at": 1024, "ch": 1, "rate": 48000},
            rec="synth-impulse",
            cls="window-boundary-impulse",
            rate=48_000,
            layout="mono",
            samples=2048,
            derivation="impulse at sample 1024 (frame boundary)",
        ),
        synth(
            "synth-impulse-1025",
            {"fn": "impulse", "n": 2048, "at": 1025, "ch": 1, "rate": 48000},
            rec="synth-impulse",
            cls="window-boundary-impulse",
            rate=48_000,
            layout="mono",
            samples=2048,
            derivation="impulse at sample 1025",
        ),
        synth(
            "synth-impulse-final",
            {"fn": "impulse", "n": 2048, "at": 2047, "ch": 1, "rate": 48000},
            rec="synth-impulse",
            cls="window-boundary-impulse",
            rate=48_000,
            layout="mono",
            samples=2048,
            derivation="impulse at final sample",
        ),
        synth(
            "synth-dc",
            {"fn": "dc", "n": 2048, "value": 0.25, "ch": 1, "rate": 48000},
            rec="synth-dc",
            cls="dc",
            rate=48_000,
            layout="mono",
            samples=2048,
            derivation="constant 0.25",
        ),
        synth(
            "synth-fullscale",
            {"fn": "fullscale", "n": 1024, "ch": 1, "rate": 48000},
            rec="synth-fullscale",
            cls="full-scale",
            rate=48_000,
            layout="mono",
            samples=1024,
            derivation="all +1.0",
        ),
        synth(
            "synth-clipped",
            {"fn": "clipped", "n": 1024, "ch": 1, "rate": 48000},
            rec="synth-clipped",
            cls="clipped",
            rate=48_000,
            layout="mono",
            samples=1024,
            derivation="±1.5 beyond full scale",
        ),
        synth(
            "synth-antiphase-stereo",
            {"fn": "antiphase", "n": 2048, "rate": 48000},
            rec="synth-antiphase",
            cls="anti-phase-stereo",
            rate=48_000,
            layout="stereo",
            samples=2048,
            derivation="L = -R 440 Hz",
        ),
        synth(
            "synth-short-0",
            {"fn": "empty", "n": 0, "ch": 1, "rate": 48000},
            rec="synth-short",
            cls="very-short",
            rate=48_000,
            layout="mono",
            samples=0,
            derivation="0 samples",
        ),
        synth(
            "synth-short-1",
            {"fn": "one_sample", "n": 1, "ch": 1, "rate": 48000},
            rec="synth-short",
            cls="very-short",
            rate=48_000,
            layout="mono",
            samples=1,
            derivation="1 sample",
        ),
        synth(
            "synth-short-1023",
            {"fn": "silence", "n": 1023, "ch": 1, "rate": 48000},
            rec="synth-short",
            cls="very-short",
            rate=48_000,
            layout="mono",
            samples=1023,
            derivation="1023 samples (one less than a frame)",
        ),
        synth(
            "synth-short-1025",
            {"fn": "silence", "n": 1025, "ch": 1, "rate": 48000},
            rec="synth-short",
            cls="very-short",
            rate=48_000,
            layout="mono",
            samples=1025,
            derivation="1025 samples (one more than a frame)",
        ),
        synth(
            "synth-mc51-ch-impulses",
            {
                "fn": "impulse",
                "n": 2048,
                "at": 0,
                "ch": 6,
                "which": 0,
                "rate": 48000,
            },
            rec="synth-mc51-impulse",
            cls="multichannel-impulse",
            rate=48_000,
            layout="5.1",
            samples=2048,
            derivation="FL impulse, other 5.1 planes silent (LFE index 3 empty)",
        ),
        synth(
            "synth-long-stream-tone",
            {"fn": "tone", "n": 48000 * 8, "ch": 1, "rate": 48000, "freq": 1000.0},
            rec="synth-long-tone",
            cls="long-stream",
            rate=48_000,
            layout="mono",
            samples=48000 * 8,
            derivation="8 s 1 kHz tone (generated, not stored)",
        ),
        synth(
            "synth-8k-tone",
            {"fn": "tone", "n": 8000, "ch": 1, "rate": 8000, "freq": 440.0},
            rec="synth-8k",
            cls="tonal",
            rate=8_000,
            layout="mono",
            samples=8000,
            derivation="8 kHz rate cell",
        ),
        synth(
            "synth-96k-impulse",
            {"fn": "impulse", "n": 2048, "at": 0, "ch": 1, "rate": 96000},
            rec="synth-96k",
            cls="window-boundary-impulse",
            rate=96_000,
            layout="mono",
            samples=2048,
            derivation="96 kHz rate cell",
        ),
        synth(
            "synth-ambience-noise",
            {"fn": "noise", "n": 48000, "ch": 2, "rate": 48000, "seed": 7},
            rec="synth-ambience",
            cls="ambience",
            rate=48_000,
            layout="stereo",
            samples=48000,
            derivation="uncorrelated stereo noise",
        ),
        synth(
            "synth-sibilant-hf",
            {"fn": "tone", "n": 48000, "ch": 1, "rate": 48000, "freq": 7000.0},
            rec="synth-sibilant",
            cls="sibilant-like",
            rate=48_000,
            layout="mono",
            samples=48000,
            derivation="7 kHz tone as sibilant stand-in (not a natural /s/)",
        ),
        synth(
            "synth-sweep",
            {"fn": "sweep", "n": 48000, "ch": 1, "rate": 48000},
            rec="synth-sweep",
            cls="tonal",
            rate=48_000,
            layout="mono",
            samples=48000,
            derivation="quadratic chirp",
        ),
    ]

    # 24 natural excerpts: identified, not vendored. Distinct recording_id.
    # Holdout: 8 of 24 recordings (one-third).
    naturals = [
        (
            "nat-librispeech-1089",
            "openslr12-spk-1089",
            "speech-voiced",
            "https://www.openslr.org/12/",
            "CC BY 4.0 (LibriSpeech)",
            "dev",
            16_000,
            "mono",
            "en",
            "LibriSpeech test-clean speaker 1089; obtain flac offline, do not vendor",
        ),
        (
            "nat-librispeech-1188",
            "openslr12-spk-1188",
            "speech-voiced",
            "https://www.openslr.org/12/",
            "CC BY 4.0 (LibriSpeech)",
            "dev",
            16_000,
            "mono",
            "en",
            "LibriSpeech test-clean speaker 1188",
        ),
        (
            "nat-librispeech-1221",
            "openslr12-spk-1221",
            "speech-unvoiced",
            "https://www.openslr.org/12/",
            "CC BY 4.0 (LibriSpeech)",
            "dev",
            16_000,
            "mono",
            "en",
            "LibriSpeech test-clean speaker 1221 (unvoiced-rich read speech)",
        ),
        (
            "nat-librispeech-1284",
            "openslr12-spk-1284",
            "speech-sibilants",
            "https://www.openslr.org/12/",
            "CC BY 4.0 (LibriSpeech)",
            "dev",
            16_000,
            "mono",
            "en",
            "LibriSpeech test-clean speaker 1284",
        ),
        (
            "nat-librispeech-1320",
            "openslr12-spk-1320",
            "speech-voiced",
            "https://www.openslr.org/12/",
            "CC BY 4.0 (LibriSpeech)",
            "dev",
            16_000,
            "mono",
            "en",
            "LibriSpeech test-clean speaker 1320",
        ),
        (
            "nat-librispeech-121",
            "openslr12-spk-121",
            "speech-voiced",
            "https://www.openslr.org/12/",
            "CC BY 4.0 (LibriSpeech)",
            "dev",
            16_000,
            "mono",
            "en",
            "LibriSpeech test-clean speaker 121",
        ),
        (
            "nat-librispeech-2961",
            "openslr12-spk-2961",
            "speech-voiced",
            "https://www.openslr.org/12/",
            "CC BY 4.0 (LibriSpeech)",
            "dev",
            16_000,
            "mono",
            "en",
            "LibriSpeech test-clean speaker 2961",
        ),
        (
            "nat-librispeech-3575",
            "openslr12-spk-3575",
            "speech-voiced",
            "https://www.openslr.org/12/",
            "CC BY 4.0 (LibriSpeech)",
            "dev",
            16_000,
            "mono",
            "en",
            "LibriSpeech test-clean speaker 3575",
        ),
        (
            "nat-openslr-yesno",
            "openslr1-yesno",
            "speech-voiced",
            "https://www.openslr.org/1/",
            "CC0 (OpenSLR waves_yesno)",
            "dev",
            8_000,
            "mono",
            "he",
            "OpenSLR resource 1 Hebrew yes/no; one speaker identity",
        ),
        (
            "nat-cv-de",
            "commonvoice-de-corpus",
            "speech-voiced",
            "https://commonvoice.mozilla.org/en/datasets",
            "CC0 (Common Voice)",
            "dev",
            48_000,
            "mono",
            "de",
            "Mozilla Common Voice German validated clip; obtain from official dump",
        ),
        (
            "nat-cv-fr",
            "commonvoice-fr-corpus",
            "speech-voiced",
            "https://commonvoice.mozilla.org/en/datasets",
            "CC0 (Common Voice)",
            "dev",
            48_000,
            "mono",
            "fr",
            "Mozilla Common Voice French validated clip",
        ),
        (
            "nat-cv-zh",
            "commonvoice-zh-cn-corpus",
            "speech-sibilants",
            "https://commonvoice.mozilla.org/en/datasets",
            "CC0 (Common Voice)",
            "dev",
            48_000,
            "mono",
            "zh-CN",
            "Mozilla Common Voice Chinese validated clip",
        ),
        (
            "nat-musopen-beethoven5",
            "musopen-beethoven-sym5",
            "tonal-music",
            "https://archive.org/details/musopen",
            "Public domain (Musopen)",
            "dev",
            44_100,
            "stereo",
            "n/a",
            "Musopen Beethoven Symphony 5 recording on archive.org",
        ),
        (
            "nat-musopen-bach-cello",
            "musopen-bach-cello1",
            "tonal-music",
            "https://archive.org/details/musopen",
            "Public domain (Musopen)",
            "dev",
            44_100,
            "stereo",
            "n/a",
            "Musopen Bach Cello Suite 1",
        ),
        (
            "nat-nasa-apollo11",
            "nasa-apollo11-landing",
            "speech-radio",
            "https://archive.org/details/Apollo11Audio",
            "Public domain (US government)",
            "dev",
            11_025,
            "mono",
            "en",
            "Apollo 11 landing loop; public domain NASA audio",
        ),
        (
            "nat-nasa-saturnv",
            "nasa-saturnv-launch",
            "percussion-transient",
            "https://images.nasa.gov/",
            "Public domain (US government)",
            "dev",
            48_000,
            "stereo",
            "n/a",
            "Saturn V launch recording; obtain from NASA image/audio catalog",
        ),
        # Holdout (8 recordings): never use neighboring excerpts from the same id in dev.
        (
            "nat-librispeech-1580",
            "openslr12-spk-1580",
            "speech-voiced",
            "https://www.openslr.org/12/",
            "CC BY 4.0 (LibriSpeech)",
            "holdout",
            16_000,
            "mono",
            "en",
            "HOLD OUT: LibriSpeech test-clean speaker 1580",
        ),
        (
            "nat-librispeech-1995",
            "openslr12-spk-1995",
            "speech-voiced",
            "https://www.openslr.org/12/",
            "CC BY 4.0 (LibriSpeech)",
            "holdout",
            16_000,
            "mono",
            "en",
            "HOLD OUT: LibriSpeech test-clean speaker 1995",
        ),
        (
            "nat-librispeech-2094",
            "openslr12-spk-2094",
            "speech-sibilants",
            "https://www.openslr.org/12/",
            "CC BY 4.0 (LibriSpeech)",
            "holdout",
            16_000,
            "mono",
            "en",
            "HOLD OUT: LibriSpeech test-clean speaker 2094",
        ),
        (
            "nat-cv-ar",
            "commonvoice-ar-corpus",
            "speech-voiced",
            "https://commonvoice.mozilla.org/en/datasets",
            "CC0 (Common Voice)",
            "holdout",
            48_000,
            "mono",
            "ar",
            "HOLD OUT: Mozilla Common Voice Arabic",
        ),
        (
            "nat-musopen-chopin",
            "musopen-chopin-op28",
            "tonal-music",
            "https://archive.org/details/musopen",
            "Public domain (Musopen)",
            "holdout",
            44_100,
            "stereo",
            "n/a",
            "HOLD OUT: Musopen Chopin prelude recording",
        ),
        (
            "nat-cv-ja",
            "commonvoice-ja-corpus",
            "speech-unvoiced",
            "https://commonvoice.mozilla.org/en/datasets",
            "CC0 (Common Voice)",
            "holdout",
            48_000,
            "mono",
            "ja",
            "HOLD OUT: Mozilla Common Voice Japanese",
        ),
        (
            "nat-librivox-war",
            "librivox-war-of-the-worlds",
            "speech-voiced",
            "https://librivox.org/the-war-of-the-worlds-by-h-g-wells/",
            "Public domain (LibriVox)",
            "holdout",
            22_050,
            "mono",
            "en",
            "HOLD OUT: LibriVox War of the Worlds; whole recording identity reserved",
        ),
        (
            "nat-fma-percussion",
            "fma-cc0-percussion",
            "percussion-transient",
            "https://freemusicarchive.org/",
            "CC0 (Free Music Archive, per-track license must be rechecked)",
            "holdout",
            44_100,
            "stereo",
            "n/a",
            "HOLD OUT: CC0 percussion track; re-verify license at obtain time",
        ),
    ]
    for row in naturals:
        (
            cid,
            rec,
            cls,
            url,
            lic,
            split,
            rate,
            layout,
            lang,
            note,
        ) = row
        out.append(
            natural(
                cid,
                rec=rec,
                cls=cls,
                origin_url=url,
                license=lic,
                split=split,
                rate=rate,
                layout=layout,
                note=note,
                languages=lang,
            )
        )
    return out


def main() -> int:
    c = cases()
    man = {
        "version": 1,
        "title": "syom AAC evaluation corpus",
        "offline": True,
        "notes": (
            "In-tree goldens and generated PCM are hashed and verified offline. "
            "Natural excerpts are identified with origin/license/recording_id but "
            "are not vendored (network was unavailable / redistribution refused). "
            "presence=gap-until-obtained. Ordinary cargo tests must not require them."
        ),
        "cases": c,
    }
    dest = ROOT / "corpus" / "manifest.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(man, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {dest} ({len(c)} cases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
